name: cubetrone
description: a flutter app to control cubetrone cubes using bluetooth.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_reorderable_grid_view: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  background_image: images/splash.png
  android: true
  android_gravity: center